---
title: World's Greatest Monty Hall Simulation App
author: Nathaniel Woodward
date: '2019-06-19'
slug: worlds-greatest-monty-hall-simulation-app
categories: []
tags: []
---

A couple months ago a colleague and I volunteered for some outreach at a local science museum. It was for an 21+ night (i.e., lots of nerdy adults drinking beers together) and the theme was "Get Your Game On". As we are both faculty in the Department of Statistics and Data Sciences, we were spoiled for choice, but finally decided to set up a Monty Hall station where people would come by and play a version of the notoriously confusing Let's Make a Deal game (the original car/goat scenario). I decided to make a [Shiny app](https://nraley.shinyapps.io/MontyHall/) to animate the scenario (you might want to adjust your speakers...) and to keep track of the proportion of wins if people switched doors versus if they chose to stay with their original door. I also included a simulation that allows you to iterate the game more quickly so you can see how the proportions diverge. Finally, I added an explanation tab, but for some reason it broke the app, so I have included it separately and linked to it via the app. 

You can play with it yourself below!

## Check it out!

https://nraley.shinyapps.io/MontyHall/